# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
SbSendboxBundle:
    resource: "@SbSendboxBundle/Resources/config/routing.yml"
    prefix: /