security:
    access_decision_manager:
        strategy:             affirmative
        allow_if_all_abstain:  false
        allow_if_equal_granted_denied:  true
    providers:
        administrators:
            memory: ~
    firewalls:
        admin_area:
            pattern:    ^/admin
            http_basic: ~